apiVersion: v1
kind: Secret
metadata:
  name: {{ include "twitter-deleter.fullname" . }}-twitter-credentials
  labels:
    {{- include "twitter-deleter.labels" . | nindent 4 }}
stringData:
  {{- with .Values.credentials }}
    access_token: {{ .accessToken }}
    access_token_secret: {{ .accessTokenSecret }} 
    bearer_token: {{ .bearerToken }}
    consumer_secret: {{ .consumerSecret }}
    consumer_token: {{ .consumerToken }} 
    username: {{ .username }}
  {{ end -}}