apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: twitter-deleter
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://gitlab.com/wesj_org/twitter-deleter.git'
    path: k8s/prod
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true