kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: logs-data
spec:
  storageClassName: local-path
  selector:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi