apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# used tagged versions for reproducible builds
resources:
  - "https://gitlab.com/wesj_org/twitter-deleter/-/raw/1.0.0.0/k8s/base/cronjob.yml"
  - "https://gitlab.com/wesj_org/twitter-deleter/-/raw/1.0.0.0/k8s/base/pvc.yml"

# you could remove this line above and use your own PVC definition yaml, if you wish.

commonLabels:
  app: twitter-deleter
  appVersion: 1.0.0.0
  release: example

# adjust image used here
images:
  - name: twitter-deleter
    newName: your-registry.example.com/wesjorg/twitter-deleter
    newTag: 1.0.0.0

# edit config here
configMapGenerator:
  - name: twitter-deleter-config
    literals:
      - DRY_RUN=false
      - DAYS_TO_KEEP=3
      - SECRETS_DIR=/secrets

# add twitter credentials here (or add them separately)
secretGenerator:
  - name: twitter-credentials
    literals:
      - access_token="get this from the twitter developer site"
      - access_token_secret="get this from the twitter developer site"
      - consumer_secret="get this from the twitter developer site"
      - consumer_token="get this from the twitter developer site"
      - username="yourusername123"

# use JSONPatches to update registry credentials adjust run schedule
patches:
  -   target:
        kind: CronJob
      patch: |-
        - op: replace
          path: /spec/jobTemplate/spec/template/spec/imagePullSecrets
          value:
            - name: your-registry-example-com-creds
        - op: replace
          path: /spec/schedule
          value: "0 * * * *"